# Generated by Django 6.0 on 2025-12-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0006_alter_complaint_sender_alter_compliment_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereddish',
            old_name='dish',
            new_name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('food', 'Food'), ('merch', 'Merch')], default='food', max_length=5),
        ),
        migrations.RenameModel(
            old_name='Dish',
            new_name='Product',
        ),
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.product')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.employee')),
            ],
            options={
                'unique_together': {('product', 'who')},
            },
        ),
        migrations.DeleteModel(
            name='DishRating',
        ),
    ]
