# Generated by Django 6.0 on 2025-12-11 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0007_rename_dish_ordereddish_product_order_order_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='chef',
        ),
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='air.chef'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('food', 'Food'), ('merch', 'Merch')], default='food', max_length=10),
        ),
    ]
